### ISSUE TITLE
rm_chassis_controllers包编译报错问题

### ISSUE THREAD

**Issue by milchstrasse565** [rm-controls/rm_control#101]
您好，我留意到ros源中的rm_chassis_controllers包已不存在，所以我将该包从仓库下载进行编译但是编译报错，报错截图如下：
![2023-02-12_13-52](https://user-images.githubusercontent.com/110643225/218295371-05434eab-904a-4bcb-a2a9-bce9b77b4620.png)

**Comment by ye-luo-xi-tui** [comment]
从源码编译rm_control再去编译这个包应该能解决。这个msg被改了，还没更新到源。

**Comment by ye-luo-xi-tui** [comment]
issue我先关了，还有问题可以再开
