### ISSUE TITLE
关于rm_gazebo中的rmuc场地文件

### ISSUE THREAD

**Issue by popfishy** [rm-controls/rm_control#121]
<geometry>
          <mesh>
            <uri>model://rmuc_2022/meshes/place.dae</uri>
            <scale>0.001 0.001 0.001</scale>
          </mesh>
        </geometry>
此处是将真实比赛场地缩小到原来的千分之一，然后再加载到gazebo中吗？  那么如果我用此模型SLAM仿真建图的话，最终得到的地图是否同样需要放大1000倍？   最后想请问是使用什么软件将模型转换成.dae文件的？

**Comment by popfishy** [comment]
> 我也不太清楚这三个0.001的含义。另外我们的这个场地由于细节太多，运行时非常卡，可以尝试这个开源https://github.com/HBUTHUANGPX/Hbut_LC_sentry 最后转换dae文件的软件我也不太清楚，因为是师兄留给我们的遗产了


好吧，我感觉应该是导出的是mm， 多谢了。我去试试你们的新模型

**Comment by ye-luo-xi-tui** [comment]
> > 我也不太清楚这三个0.001的含义。另外我们的这个场地由于细节太多，运行时非常卡，可以尝试这个开源https://github.com/HBUTHUANGPX/Hbut_LC_sentry 最后转换dae文件的软件我也不太清楚，因为是师兄留给我们的遗产了
> 
> 好吧，我感觉应该是导出的是mm， 多谢了。我去试试你们的新模型

不是我们的，是湖工大开源的hhh
