### ISSUE TITLE
chassis_controller中pid的output输出很小

### ISSUE THREAD

**Issue by milchstrasse565** [rm-controls/rm_control#204]
测试装有4个2006电机的麦轮小车
 硬件接口改成了type: rm_2006
四个轮子的坐标和半径都改了
actuator_states中2006的角速度、角度值都正确
但是上车时观察pid的output以及轮子的command都接近0

**Comment by ye-luo-xi-tui** [comment]
可观察pid的error，p_term是否正确。确认/cmd_vel /cmd_chassis有无正确发送。另外是否有跑通仿真？

**Comment by milchstrasse565** [comment]
如图，/cmd_vel /cmd_chassis都已正确发送，只有p控制，p_term和output输出值一样，输出值几乎为0，但我用手转动麦轮时会有0.1左右的输出
![201_1699866398_hd](https://github.com/rm-controls/rm_control/assets/110643225/8d5b3e41-50d2-4ba3-bc49-76c321abe0df)

**Comment by ye-luo-xi-tui** [comment]
速度的设定值一直是0，/cmd_chassis里要设置加速度和限制功率，从你的图中并没有看到/cmd_chassis的内容

**Comment by milchstrasse565** [comment]
你好，这张图可以看到
![202_1699867848_hd](https://github.com/rm-controls/rm_control/assets/110643225/ec6ff8f9-51d7-4bef-85f8-27c3febf389a)

**Comment by ye-luo-xi-tui** [comment]
> 你好，这张图可以看到 ![202_1699867848_hd](https://user-images.githubusercontent.com/110643225/282419755-ec6ff8f9-51d7-4bef-85f8-27c3febf389a.jpeg)

topic改成/cmd_chassis了，你可以用rostopic list看一下

**Comment by milchstrasse565** [comment]
已经解决！谢谢！对不起没有查看topic

**Comment by milchstrasse565** [comment]
佬你好我想请教一下，我看了看底层，运动解算最后setCommand发布了目标速度，但是我没看到在哪个位置获取了参数文件中的  pid: { p: 0.6 , i: 0, d: 0 , i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }，也不知道当前测量值在哪里获取的，是执行器吗
