### ISSUE TITLE
官方文档Gazebo底盘部分：仿真中底盘无法运动

### ISSUE THREAD

**Issue by Emptory** [rm-controls/rm_control#220]
您好，在使用官方文档教程的gazebo底盘部分时，我遇到了一些问题

1. 在rqt中启动chassis_controller后，gazebo提示报错
![图片](https://github.com/rm-controls/rm_control/assets/50489512/da558934-92b3-4e48-99f7-d47a5276eff0)
2. 之后，我按照文档发布`rm_msgs/ChassisCmd`和`/cmd_vel geometry_msgs/Twist`，并且通过`rostopic echo`检测，两个话题均正常发布，但是仿真的底盘没有运动
3.  我尝试了舵轮和麦克纳姆轮，以及三种模式，仿真中底盘均不运动，一开始我以为是`yaw`的问题，
4. 我尝试修改了`chassis_base.cpp`
```c++
if (cmd_rt_buffer_.readFromRT()->cmd_chassis_.follow_source_frame.empty())
    follow_source_frame_ = "map";
  else
    follow_source_frame_ = cmd_rt_buffer_.readFromRT()->cmd_chassis_.follow_source_frame;
  if (cmd_rt_buffer_.readFromRT()->cmd_chassis_.command_source_frame.empty())
    command_source_frame_ = "map";
  else
    command_source_frame_ = cmd_rt_buffer_.readFromRT()->cmd_chassis_.command_source_frame;
```
但是无效，尽管1中所述warning消失，但文档设置底盘运动模式和速度后，仿真中底盘依然无法运动，我在查看了已有的issue后，也显示这个问题似乎和yaw的warning并没有关系

我想请问一下，这可能是由于什么原因导致的。

**Comment by ye-luo-xi-tui** [comment]
chassCmd发布在/cmd_chassis，可以检查是否发错话题。一些接口可能发生改变，文档不一定有更新

**Comment by WiseL00k** [comment]
我也遇到了这个问题，出现一样的报错并且底盘无法运动，请问后续解决了吗？

**Comment by ye-luo-xi-tui** [comment]
> 我也遇到了这个问题，出现一样的报错并且底盘无法运动，请问后续解决了吗？

广工的？在做考核吗😂

**Comment by WiseL00k** [comment]
> > 我也遇到了这个问题，出现一样的报错并且底盘无法运动，请问后续解决了吗？
> 
> 广工的？在做考核吗😂

被发现了[doge],不过我们才刚开ROS，还没开始考核。

**Comment by WiseL00k** [comment]
![图片](https://github.com/user-attachments/assets/264ac8cb-cfa5-4c97-abd4-c8f8a79ccc54)
我通过将 设置底盘的各种参数 这一节中的话题名称改为/cmd_chassis解决了问题，yaw的warning仍然存在，但是底盘可以运动了。
