### ISSUE TITLE
关于无下位机的疑问

### ISSUE THREAD

**Issue by nickyyy28** [rm-controls/rm_control#9]
在https://rm-controls.github.io/ 这个链接中看到了关于这个项目的介绍, 
我注意到了在该项目中, 是无需下位机, 是指没有类似于stm32等mcu用作控制对吧, 但是假如像哨兵这种全自动的机器人, 肯定是需要外置光电传感器的, 像这种需要外置传感器的硬件, 是怎么集成到一个电脑上的呢?

**Comment by qiayuanliao** [comment]
> 在https://rm-controls.github.io/ 这个链接中看到了关于这个项目的介绍,
> 我注意到了在该项目中, 是无需下位机, 是指没有类似于stm32等mcu用作控制对吧, 但是假如像哨兵这种全自动的机器人, 肯定是需要外置光电传感器的, 像这种需要外置传感器的硬件, 是怎么集成到一个电脑上的呢?

IO能力是这个项目最大的缺点，2021 赛季我们几乎不使用 GPIO和 SPI IIC，不过我们也有开发了部分转接模块，今后针对IO能力的开发计划可以见  [Road Map](https://rm-controls.github.io/overview/road_map#io)

**Comment by nickyyy28** [comment]
好的, 谢谢大佬的解答
