### ISSUE TITLE
配置运行rm_hw出现报错

### ISSUE THREAD

**Issue by Que121** [rm-controls/rm_control#96]
您好，在使用教程进行配置运行rm_hw时出现如下报错
![2023-01-30_21-03](https://user-images.githubusercontent.com/97080652/215485806-0aef108e-3e2a-47da-8fdb-399cd8e2a381.png)

**Comment by ye-luo-xi-tui** [comment]
请检查参数服务器是否有这三个参数：loop_hz,cycle_time_error_threshold,thread_priority。

**Comment by Que121** [comment]
收到了，谢谢！

**Comment by Que121** [comment]
检查后，发现只存在cycle_time_error_threshold
![2023-01-30_21-14](https://user-images.githubusercontent.com/97080652/215487675-a44fe775-a43c-484c-a36d-56ebe12a68ce.png)

**Comment by Que121** [comment]
您好，/rm_hw可以成功运行，但是加载控制器出现错误，应该也是文档中没有更新。
![2023-01-30_21-48](https://user-images.githubusercontent.com/97080652/215495573-3aa1a706-7aef-47bd-81f2-6b9ad9900adb.png)

**Comment by ye-luo-xi-tui** [comment]
> 您好，/rm_hw可以成功运行，但是加载控制器出现错误，应该也是文档中没有更新。 ![2023-01-30_21-48](https://user-images.githubusercontent.com/97080652/215495573-3aa1a706-7aef-47bd-81f2-6b9ad9900adb.png)

我不这么认为，第一个报错是该控制器已经加载进去了。剩下的控制器是ros_control提供的，报错信息说找不到这些类型的控制器，可能是你没有安装相关包

**Comment by Que121** [comment]
我使用了仓库中给出的命令从源安装了包，但是没有解决问题。可能是仍未安装相关的包，可以告知具体的包该如何安装吗？谢谢！

**Comment by ye-luo-xi-tui** [comment]
[![8rpgd.png](https://i.328888.xyz/2023/01/31/8rpgd.png)](https://imgloc.com/i/8rpgd)
使用这条指令查看可用的控制器类型
你要加载的控制器来自这个软件包https://github.com/ros-controls/ros_controllers

**Comment by Que121** [comment]
您好，在此之前已经查看过，不存在需要的两种控制器，可以告知如何从源安装这个包吗？
![Uploading 2023-01-31_12-26.png…]()

**Comment by ye-luo-xi-tui** [comment]
> 您好，在此之前已经查看过，不存在需要的两种控制器，可以告知如何从源安装这个包吗？ ![2023-01-31_12-26](https://user-images.githubusercontent.com/97080652/215665596-ea18661d-4233-4df0-86c1-51efea181fad.png)

和其他软件包一样，你知道软件包的名字之后直接用apt装就可以了，只是下划线替换成横杠。可以试试ros_controllers这个元包或effort_controllers这个子包

**Comment by ye-luo-xi-tui** [comment]
> > 您好，在此之前已经查看过，不存在需要的两种控制器，可以告知如何从源安装这个包吗？ ![2023-01-31_12-26](https://user-images.githubusercontent.com/97080652/215665596-ea18661d-4233-4df0-86c1-51efea181fad.png)
> 
> 和其他软件包一样，你知道软件包的名字之后直接用apt装就可以了，只是下划线替换成横杠。可以试试ros_controllers这个元包或effort_controllers这个子包

可多尝试用TAB补全

**Comment by Que121** [comment]
已经解决问题，谢谢！
