### ISSUE TITLE
官方文档中gazebo底盘部分存在bug

### ISSUE THREAD

**Issue by Que121** [rm-controls/rm_control#98]
使用官方文档中gazebo底盘部分出现如下问题：
(设置底盘为英雄底盘)
**1.** 根据文档，设置底盘运动模式为FOLLOW，使用文档提供的命令操控底盘，底盘未直线运动，而是自旋，使用实物时出现相同情况
![2023-02-02_21-55](https://user-images.githubusercontent.com/97080652/216344371-7ee57d09-afb4-4f67-bab4-1dadb4fcf741.png)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=112687994927960524 skey=@crypt_4ea6157d_3d36aff3bc8a8db41390187bd3d81271 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/97080652/216345174-87a5eaba-2f94-4d49-9d05-e35906151eef.jpeg)

https://user-images.githubusercontent.com/97080652/216346685-6f7a97c8-0352-4215-8534-fa05a0881b56.mp4

**2.** 当底盘运动模式为FOLLOW时，只给z轴角速度设有正值，其他都为零，底盘直线运动，实物和仿真情况相同。
![2023-02-02_22-04](https://user-images.githubusercontent.com/97080652/216346105-71a0f594-7103-4642-a6bd-2078afd8ac47.png)

https://user-images.githubusercontent.com/97080652/216346728-af5262c9-1f8e-45dc-9849-2328aacd3902.mp4

**3.** 使用rm_hw运行底盘实物，rm_hw存在如下warning
![2023-02-02_22-03](https://user-images.githubusercontent.com/97080652/216345768-1f1b8c61-1ef8-46dc-9945-69a8c3c1dde2.png)

**Comment by ye-luo-xi-tui** [comment]
follow模式会使底盘跟随某一坐标系，主要用于底盘跟随云台。我注意到你无论是仿真还是实物都没有云台。可以试试raw模式（该模式将速度指令视为底盘坐标系下。）或在仿真中仿真整车后再尝试follow模式

**Comment by Que121** [comment]
您好，使用raw模式仍为自旋，而且我注意到文档中说明raw模式下底盘无法运动
![2023-02-02_22-39](https://user-images.githubusercontent.com/97080652/216355337-c21ee1b0-7d76-4022-9cb2-b477ae7a066b.png)

![2023-02-02_22-36](https://user-images.githubusercontent.com/97080652/216355373-39893edb-c0cf-49b3-95b9-771cd9c559ee.png)

**Comment by ye-luo-xi-tui** [comment]
> 您好，使用raw模式仍为自旋，而且我注意到文档中说明raw模式下底盘无法运动 ![2023-02-02_22-39](https://user-images.githubusercontent.com/97080652/216355337-c21ee1b0-7d76-4022-9cb2-b477ae7a066b.png)
> 
> ![2023-02-02_22-36](https://user-images.githubusercontent.com/97080652/216355373-39893edb-c0cf-49b3-95b9-771cd9c559ee.png)

这里写错了，需要修

**Comment by ye-luo-xi-tui** [comment]
> 能否查看/cmd_vel和/controllers/chassis_controller/command这两个话题和四个轮子实际运动表现和/joint_state中显示的四个轮子转速以便于debug？

可先在仿真进行

**Comment by ye-luo-xi-tui** [comment]
> > 能否查看/cmd_vel和/controllers/chassis_controller/command这两个话题和四个轮子实际运动表现和/joint_state中显示的四个轮子转速以便于debug？
> 
> 可先在仿真进行

如果仿真的urdf用的是我们提供的，请在gazebo仿真时顺便将坐标系显示出来以让我辨认对应轮子，谢谢！

**Comment by Que121** [comment]
您好，使用的的urdf为官方仓库提供的英雄底盘。
FOLLOW模式：
![2023-02-03_11-22](https://user-images.githubusercontent.com/97080652/216506997-f926af57-78c4-4c5b-823e-748848cab4c5.png)
![2023-02-03_11-23](https://user-images.githubusercontent.com/97080652/216507016-dcd2c94f-330d-4092-9a8c-4534802a5dac.png)
但轮子转速应该由/controllers/chassis_controller/wheels/*/state显示？

https://user-images.githubusercontent.com/97080652/216507231-deb2a7c2-6832-4b61-ae6c-edd4a1fc30f1.mp4

**Comment by ye-luo-xi-tui** [comment]
> 您好，使用的的urdf为官方仓库提供的英雄底盘。 FOLLOW模式： ![2023-02-03_11-22](https://user-images.githubusercontent.com/97080652/216506997-f926af57-78c4-4c5b-823e-748848cab4c5.png) ![2023-02-03_11-23](https://user-images.githubusercontent.com/97080652/216507016-dcd2c94f-330d-4092-9a8c-4534802a5dac.png) 但轮子转速应该由/controllers/chassis_controller/wheels/*/state显示？
> 
>  2023-02-03.11.36.21.mp4

把mode改为0，即raw模式试试看

**Comment by ye-luo-xi-tui** [comment]
如果觉得这种沟通方式效率不高，你也可以自己打断点debug。在仿真中调试底盘控制器时用`attach to process` attach 到 `gzsever`，即可对底盘控制器代码打断点。https://www.jetbrains.com/help/clion/attaching-to-local-process.html

**Comment by milchstrasse565** [comment]
我把mode改为0，raw模式也是一样的情况，x线速度自旋，z角速度直线走，x和z同时给，就原地绕圈+旋转诶

**Comment by ye-luo-xi-tui** [comment]
我知道原因了，是配置文件错误导致运动学错误。我们将全向轮与麦克纳姆轮的运动学进行了统一。你所使用的配置文件是全向轮的配置，麦克纳姆轮需将相应配置修改如下：https://github.com/rm-controls/rm_config/blob/bcca860bbec206ac69077f5363ae9ffff21b671c/config/rm_controllers/hero.yaml#L33-L56

**Comment by milchstrasse565** [comment]
您好，我看你们的步兵用的是舵轮，这个全向轮的运动学是不是舵轮的运动学

**Comment by ye-luo-xi-tui** [comment]
> 您好，我看你们的步兵用的是舵轮，这个全向轮的运动学是不是舵轮的运动学

我们22赛季步兵就是全向轮

**Comment by Que121** [comment]
问题已经解决，十分感谢！
